// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewProject struct {
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	Contributors []string `json:"contributors"`
}

type NewUser struct {
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Username  *string `json:"username,omitempty"`
	Password  string  `json:"password"`
	Email     string  `json:"email"`
}

type Project struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Description  string  `json:"description"`
	Owner        *User   `json:"owner"`
	Contributors []*User `json:"contributors"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Username  string `json:"username"`
	Email     string `json:"email"`
}
