// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AllProjects struct {
	Public       []*Project `json:"public"`
	Owned        []*Project `json:"owned,omitempty"`
	Collaborated []*Project `json:"collaborated,omitempty"`
}

type CollabRequest struct {
	ID        string   `json:"id"`
	Project   *Project `json:"project"`
	Requester *User    `json:"requester"`
	Message   string   `json:"message"`
	Responder *User    `json:"responder,omitempty"`
	Feedback  *string  `json:"feedback,omitempty"`
	Status    string   `json:"status"`
}

type Login struct {
	Email    *string `json:"email,omitempty"`
	Username *string `json:"username,omitempty"`
	Password string  `json:"password"`
}

type Mutation struct {
}

type NewProject struct {
	Name          string   `json:"name"`
	Description   *string  `json:"description,omitempty"`
	Public        *bool    `json:"public,omitempty"`
	Collaborators []string `json:"collaborators,omitempty"`
	SkillsNeeded  []string `json:"skills_needed,omitempty"`
}

type NewTask struct {
	Task          string     `json:"task"`
	AssignedTo    []string   `json:"assignedTo,omitempty"`
	Deadline      *time.Time `json:"deadline,omitempty"`
	PriorityLevel *string    `json:"priorityLevel,omitempty"`
}

type NewUser struct {
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Username  *string  `json:"username,omitempty"`
	Password  string   `json:"password"`
	Email     string   `json:"email"`
	Skills    []string `json:"skills"`
}

type Note struct {
	ID           string    `json:"id"`
	Project      *Project  `json:"project"`
	AddedBy      *User     `json:"addedBy"`
	LastModified time.Time `json:"lastModified"`
	Note         string    `json:"note"`
}

type Project struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	Description      string   `json:"description"`
	Owner            *User    `json:"owner"`
	Public           bool     `json:"public"`
	CompletionStatus string   `json:"completionStatus"`
	Collaborators    []*User  `json:"collaborators"`
	SkillsNeeded     []string `json:"skills_needed"`
}

type Query struct {
}

type Task struct {
	ID               string     `json:"id"`
	Project          *Project   `json:"project"`
	AddedBy          *User      `json:"addedBy"`
	AssignedTo       []*User    `json:"assignedTo,omitempty"`
	Task             string     `json:"task"`
	LastModified     time.Time  `json:"lastModified"`
	Deadline         *time.Time `json:"deadline,omitempty"`
	PriorityLevel    string     `json:"priorityLevel"`
	CompletionStatus string     `json:"completionStatus"`
}

type UpdatedProject struct {
	Name             *string  `json:"name,omitempty"`
	Description      *string  `json:"description,omitempty"`
	Public           *bool    `json:"public,omitempty"`
	CompletionStatus *string  `json:"completionStatus,omitempty"`
	Collaborators    []string `json:"collaborators,omitempty"`
	SkillsNeeded     []string `json:"skills_needed,omitempty"`
}

type UpdatedTask struct {
	Task             *string    `json:"task,omitempty"`
	AssignedTo       []string   `json:"assignedTo,omitempty"`
	Deadline         *time.Time `json:"deadline,omitempty"`
	PriorityLevel    *string    `json:"priorityLevel,omitempty"`
	CompletionStatus *string    `json:"completionStatus,omitempty"`
}

type UpdatedUser struct {
	FirstName   *string  `json:"firstName,omitempty"`
	LastName    *string  `json:"lastName,omitempty"`
	Username    *string  `json:"username,omitempty"`
	OldPassword *string  `json:"old_password,omitempty"`
	NewPassword *string  `json:"new_password,omitempty"`
	Email       *string  `json:"email,omitempty"`
	Skills      []string `json:"skills,omitempty"`
}

type User struct {
	ID        string   `json:"id"`
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Username  string   `json:"username"`
	Email     string   `json:"email"`
	Skills    []string `json:"skills"`
}
